language: minimal

dist: bionic

matrix:
  fast_finish: true

jobs:
  include:
    - stage: "Prepare"
      name: "Generate unified index file"
      workspaces:
        create:
          name: build_index
          paths:
            - build_index/
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateUnifiedIndex.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions"
      workspaces:
        create:
          name: build_versions
          paths:
            - build_versions
      before_install:
        - wget http://http.us.debian.org/debian/pool/main/l/llvm-toolchain-8/libclang1-8_8.0.1-3+b1_amd64.deb
        - wget http://http.us.debian.org/debian/pool/main/n/ncurses/libtinfo6_6.1+20190803-1_amd64.deb
        - wget http://http.us.debian.org/debian/pool/main/x/xapian-core/libxapian30_1.4.12-1_amd64.deb
        - wget http://http.us.debian.org/debian/pool/main/d/doxygen/doxygen_1.8.16-1~exp2_amd64.deb
        - sudo dpkg -i libclang1-8_8.0.1-3+b1_amd64.deb
        - sudo dpkg -i libtinfo6_6.1+20190803-1_amd64.deb
        - sudo dpkg -i libxapian30_1.4.12-1_amd64.deb
        - sudo dpkg -i doxygen_1.8.16-1~exp2_amd64.deb
      addons:
        apt:
          packages:
            - graphviz
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: deploy
      name: "Deploy generated Doxygen docs to GitHub pages"
      workspaces:
        use:
          - build_index
          - build_versions
      script:
        - mv -v -t $TRAVIS_BUILD_DIR/build/ $TRAVIS_BUILD_DIR/build_index/* $TRAVIS_BUILD_DIR/build_versions/*
      deploy:
        provider: script
        skip_cleanup: true
        script: ./deployToGitHubPages.sh

