language: minimal

matrix:
  fast_finish: true

jobs:
  include:
    - stage: "Prepare"
      name: "Generate unified index file"
      workspaces:
        create:
          name: build_index
          paths:
            - build_index/
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateUnifiedIndex.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions"
      workspaces:
        create:
          name: build_versions
          paths:
            - build_versions
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: deploy
      name: "Deploy generated Doxygen docs to GitHub pages"
      workspaces:
        use:
          - build_index
          - build_versions
      script:
        - mv -v -t $TRAVIS_BUILD_DIR/build/ $TRAVIS_BUILD_DIR/build_index/* $TRAVIS_BUILD_DIR/build_develop/* $TRAVIS_BUILD_DIR/build_versions00/* $TRAVIS_BUILD_DIR/build_versions01/* $TRAVIS_BUILD_DIR/build_versions02/* $TRAVIS_BUILD_DIR/build_versions03/* $TRAVIS_BUILD_DIR/build_versions04/* $TRAVIS_BUILD_DIR/build_versions05/* $TRAVIS_BUILD_DIR/build_versions06/* $TRAVIS_BUILD_DIR/build_versions07/* $TRAVIS_BUILD_DIR/build_versions08/* $TRAVIS_BUILD_DIR/build_versions09/*
      deploy:
        provider: script
        skip_cleanup: true
        script: ./deployToGitHubPages.sh
    - stage: deploy
      name: "Deploy generated Doxygen docs to Netlify"
      language: node_js
      node_js:
        - "11"
      workspaces:
        use:
          - build_index
          - build_versions
      before_script:
        - npm install -g netlify-cli
      script:
        - mv -v -t $TRAVIS_BUILD_DIR/build/ $TRAVIS_BUILD_DIR/build_index/* $TRAVIS_BUILD_DIR/build_develop/* $TRAVIS_BUILD_DIR/build_versions00/* $TRAVIS_BUILD_DIR/build_versions01/* $TRAVIS_BUILD_DIR/build_versions02/* $TRAVIS_BUILD_DIR/build_versions03/* $TRAVIS_BUILD_DIR/build_versions04/* $TRAVIS_BUILD_DIR/build_versions05/* $TRAVIS_BUILD_DIR/build_versions06/* $TRAVIS_BUILD_DIR/build_versions07/* $TRAVIS_BUILD_DIR/build_versions08/* $TRAVIS_BUILD_DIR/build_versions09/*
      deploy:
        provider: script
        skip_cleanup: true
        script: ./deployToNetlify.sh
