language: minimal

matrix:
  fast_finish: true

jobs:
  include:
    - stage: "Prepare"
      name: "Generate unified index file"
      workspaces:
        create:
          name: build_index
          paths:
            - build_index/
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateUnifiedIndex.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr develop (nigthly)"
      workspaces:
        create:
          name: build_develop
          paths:
            - build_develop/
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForDevelop.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (1/10)"
      workspaces:
        create:
          name: build_versions00
          paths:
            - build_versions00/
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions00
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (2/10)"
      workspaces:
        create:
          name: build_versions01
          paths:
            - build_versions01/
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions01
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: deploy
      name: "Deploy generated Doxygen docs to GitHub pages"
      workspaces:
        use:
          - build_index
          - build_develop
          - build_versions00
          - build_versions01
      addons:
        apt:
          packages:
            - tree
      script:
        - cp -a $TRAVIS_BUILD_DIR/build_index/. $TRAVIS_BUILD_DIR/build/
        - cp -a $TRAVIS_BUILD_DIR/build_develop/. $TRAVIS_BUILD_DIR/build/
        - cp -a $TRAVIS_BUILD_DIR/build_versions00/. $TRAVIS_BUILD_DIR/build/
        - cp -a $TRAVIS_BUILD_DIR/build_versions01/. $TRAVIS_BUILD_DIR/build/
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: $TRAVIS_BUILD_DIR/build
        github_token: $GITHUB_API_KEY
        on:
          branch: master

