language: minimal

dist: bionic

matrix:
  fast_finish: true

jobs:
  include:
    - stage: "Prepare"
      name: "Generate unified index file"
      workspaces:
        create:
          name: build_index
          paths:
            - build_index/
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateUnifiedIndex.sh
    - stage: "Build"
      language: php
      name: "Build doxygen docs for Dolibarr versions"
      workspaces:
        create:
          name: build_versions
          paths:
            - build_versions
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      before_install: composer self-update
      install: composer require --prefer-dist --dev hschletz/doxygen-phpdoc
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: deploy
      name: "Deploy generated Doxygen docs to GitHub pages"
      workspaces:
        use:
          - build_index
          - build_versions
      script:
        - mv -v -t $TRAVIS_BUILD_DIR/build/ $TRAVIS_BUILD_DIR/build_index/* $TRAVIS_BUILD_DIR/build_versions/*
      deploy:
        provider: script
        skip_cleanup: true
        script: ./deployToGitHubPages.sh

