language: minimal

matrix:
  fast_finish: true

jobs:
  include:
    - stage: "Prepare"
      name: "Generate unified index file"
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateUnifiedIndex.sh
      deploy:
        provider: pages
        local_dir: build_index
        skip_cleanup: true
        github_token: $GITHUB_API_KEY
        keep_history: false
        on:
          branch: master
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr develop (nigthly)"
      workspaces:
        create:
          name: build_develop
          paths:
            - build_develop/
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=develop
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForDevelop.sh
      deploy:
        provider: script
        skip_cleanup: true
        script: ./deployToGitHubPages.sh
        on:
          branch: master
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (1/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions00
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
      deploy:
        provider: script
        skip_cleanup: true
        script: ./deployToGitHubPages.sh
        on:
          branch: master
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (2/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions01
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (3/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions02
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (4/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions03
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (5/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions04
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (6/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions05
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (7/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions06
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (8/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions07
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (9/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions08
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
    - stage: "Build"
      name: "Build doxygen docs for Dolibarr versions (10/10)"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      env:
        - VERSIONSFILE=versions09
      before_script: git clone https://github.com/Dolibarr/dolibarr.git
      script: ./generateDoxygenForVersions.sh
